-- Create leaves table
CREATE TABLE IF NOT EXISTS public.leaves
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    from_date date NOT NULL,
    to_date date NOT NULL,
    alternate_person character varying(100) COLLATE pg_catalog."default",
    available_on_phone boolean DEFAULT true,
    approved_by integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    credited_days numeric(4,1) DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    additional_alternate character varying(100) COLLATE pg_catalog."default",
    leave_reason character varying(255) COLLATE pg_catalog."default",
    leave_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'Paid'::character varying,
    leave_duration character varying(50) COLLATE pg_catalog."default" DEFAULT 'Full Day'::character varying,
    CONSTRAINT leaves_pkey PRIMARY KEY (id),
    CONSTRAINT leaves_status_check CHECK (status::text = ANY (ARRAY['Pending'::character varying::text, 'Approved'::character varying::text, 'Rejected'::character varying::text, 'Cancelled'::character varying::text]))
);
